use std::path::Path;

const HYPERIUM_MD: &str = r#"# This project is hosted by Hyperium

File generated by **Hyperium** (do not edit by hand: it gets regenerated). It exists so
that an assistant coding this project (`claude` launched in this folder) knows it is part
of a larger structure, and doesn't reinvent what Hyperium already handles.

You don't need to talk about Hyperium all the time: read this when one of these conventions
is in play, otherwise ignore it.

## What Hyperium is

A personal dev cockpit (single user): a sidebar of projects, per-project terminals (claude
/ ssh / ftp / server / RDP), ambient notes, and internal tools. This project (`__PROJECT__`)
is one of the projects it opens.

## The conventions that concern you

- **Wiki = the `.md` files in `docs/`, launched by Hyperium.** If a `mkdocs.yml` exists at
  the root, the project has a MkDocs wiki. Its content lives **only** in `docs/*.md`. It is
  **Hyperium** that launches it (button next to the project → `mkdocs serve`): **do not write
  a `.bat` / `.sh` launch script**, and don't put wiki content outside `docs/`.
- **Notes = `hyperium-notes/NOTES.md`, derived, never hand-maintained.** This file is written
  automatically by Hyperium from the user's voice/text braindumps. You may **read it** for
  context (intentions, decisions, tasks), but **do not rewrite it** yourself: it is
  regenerated on the Hyperium side.
- **`*.hyp` = a Hyperium launcher.** The small `.hyp` file at the root reopens the project in
  Hyperium. Leave it, don't modify it.
- **Local-only: never push to a git remote.** Versioning is local; sync goes through the
  self-hosted server / Syncthing. The user fears an accidental push: don't add a remote,
  don't run `git push`.

## Image / video generation (Hyperium provides this)

Hyperium can generate images and videos with AI (via kie.ai) and drop them straight into
this project. **Use it whenever the project needs a visual asset** (hero, illustration,
icon, short video) instead of a placeholder or an external image. The Hyperium binary
exposes a headless mode:

```
__HYPERIUM_EXE__ gen-image --model gpt-image-2 --aspect 16:9 --res 2K --out ./assets "a prompt"
__HYPERIUM_EXE__ gen-video --model seedance-2 --aspect 16:9 --dur 5 --out ./assets "a prompt"
```

- The **generated file path is printed to stdout**: capture it and reference it in your code
  (HTML/CSS/etc.).
- Pick the `--aspect` that fits the placement (wide hero = `16:9`, portrait = `9:16`, square
  = `1:1`...). Exact per-model values: `__HYPERIUM_EXE__ gen-image --list`.
- Available models:
__MODELS__
- A **per-project cap** applies (each generation costs money). If the command refuses, **do
  not loop**: tell the user.
- The API key and the cap are managed by Hyperium: you have nothing to configure.

## When in doubt

If something in the project looks like infrastructure (wiki launch, notes file, sync,
`.hyp`), assume **Hyperium handles it** before adding your own mechanism.
"#;

fn hyperium_exe() -> String {
    match std::env::current_exe() {
        Ok(p) => format!("\"{}\"", p.display()),
        Err(_) => "hyperium".to_string(),
    }
}

fn models_list() -> String {
    crate::genai::MODELS
        .iter()
        .map(|m| {
            let kind = if matches!(m.kind, crate::genai::Kind::Image) { "image" } else { "video" };
            format!(
                "  - **{}** ({}, {kind}): `--model {}`",
                m.label,
                m.provider,
                crate::genai::short_alias(m)
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

const PTR_START: &str = "<!-- hyperium:pointer:start -->";
const PTR_END: &str = "<!-- hyperium:pointer:end -->";

fn pointer_block() -> String {
    format!(
        "{PTR_START}\n\
         > This project is open in **Hyperium** (dev cockpit). Hosting and conventions \
         (wiki launched by Hyperium, `hyperium-notes/` notes, local-only): see `HYPERIUM.md` \
         at the root.\n\
         {PTR_END}\n"
    )
}

pub fn ensure(folder: &str) {
    let dir = Path::new(folder);
    if !dir.is_dir() {
        return;
    }
    let name = dir.file_name().and_then(|s| s.to_str()).unwrap_or("ce projet");
    let body = HYPERIUM_MD
        .replace("__PROJECT__", name)
        .replace("__HYPERIUM_EXE__", &hyperium_exe())
        .replace("__MODELS__", &models_list());
    write_if_changed(&dir.join("HYPERIUM.md"), &body);
    ensure_pointer(&dir.join("CLAUDE.md"));
}

fn ensure_pointer(claude_md: &Path) {
    let block = pointer_block();
    let existing = std::fs::read_to_string(claude_md).unwrap_or_default();

    let updated = if let (Some(s), Some(e)) = (existing.find(PTR_START), existing.find(PTR_END)) {
        let end = e + PTR_END.len();
        let after = existing[end..].trim_start_matches('\n');
        let sep = if after.is_empty() { "" } else { "\n" };
        format!("{}{}{}{}", &existing[..s], block, sep, after)
    } else if existing.trim().is_empty() {
        block
    } else {
        let sep = if existing.ends_with('\n') { "\n" } else { "\n\n" };
        format!("{existing}{sep}{block}")
    };

    write_if_changed(claude_md, &updated);
}

fn write_if_changed(path: &Path, content: &str) {
    if std::fs::read_to_string(path).map(|c| c == content).unwrap_or(false) {
        return;
    }
    let _ = std::fs::write(path, content);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp(tag: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!("hyperium-manifest-{}-{tag}", std::process::id()))
    }

    #[test]
    fn seeds_both_files_with_project_name() {
        let dir = tmp("seed");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        ensure(dir.to_str().unwrap());

        let sg = std::fs::read_to_string(dir.join("HYPERIUM.md")).unwrap();
        assert!(sg.contains("hosted by Hyperium"));
        assert!(sg.contains(dir.file_name().unwrap().to_str().unwrap()));
        assert!(!sg.contains("__PROJECT__"));

        let cm = std::fs::read_to_string(dir.join("CLAUDE.md")).unwrap();
        assert!(cm.contains("HYPERIUM.md"));
        assert!(cm.contains(PTR_START) && cm.contains(PTR_END));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn pointer_is_idempotent_and_keeps_user_content() {
        let dir = tmp("idemp");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let cm = dir.join("CLAUDE.md");
        std::fs::write(&cm, "# My project\n\nMy own instructions.\n").unwrap();

        ensure(dir.to_str().unwrap());
        let after_first = std::fs::read_to_string(&cm).unwrap();
        ensure(dir.to_str().unwrap());
        let after_second = std::fs::read_to_string(&cm).unwrap();

        assert_eq!(after_first, after_second, "re-run is byte-identical (write-if-changed)");
        assert_eq!(after_first.matches(PTR_START).count(), 1, "pointer added exactly once");
        assert!(after_first.starts_with("# My project"), "user content stays at the top");
        assert!(after_first.contains("My own instructions."), "user content preserved");
        assert!(after_first.trim_end().ends_with(PTR_END), "pointer sits at the end");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
